[package]
name = "rust-reborn-auth"
version = "0.1.0"
edition = "2021"

[dependencies]
rust-reborn-contracts = { path = "../../shared/contracts" }
axum = { workspace = true }
async-trait = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
sqlx = { workspace = true }
validator = { workspace = true }
jsonwebtoken = { workspace = true }
bcrypt = { workspace = true }
chrono = { workspace = true }
utoipa = { workspace = true, features = ["chrono"]}
tokio = {workspace = true}