[package]
name = "rust-reborn-core"
version = "0.1.0"
edition = "2021"

[dependencies]
rust-reborn-auth = { path = "../auth" }
rust-reborn-contracts = { path = "../../shared/contracts" }
utoipa = { workspace = true }
utoipa-swagger-ui = { workspace = true }
anyhow = { workspace = true }
thiserror = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
async-trait = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
config = { workspace = true }
dotenvy = { workspace = true }
validator = { workspace = true }
chrono = { workspace = true }
uuid = { workspace = true }
axum = { workspace = true }
sqlx = { workspace = true }
